name: CI workflow

on: pull_request

jobs:
  ci:
    runs-on: macos-10.15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Tests
        run: npm test
